-- Ledger Suit — 25. Recurring rules
--
-- The hard requirement (spec section 17) is that the same scheduled occurrence
-- can never post twice, however many times the scheduler runs. That guarantee
-- is a unique constraint on (rule_id, occurrence_date), not application logic —
-- a concurrent second run loses the insert race and skips.

create type public.recurrence_frequency as enum (
  'daily',
  'weekly',
  'monthly',
  'quarterly',
  'yearly'
);

create type public.recurring_mode as enum (
  'auto_post',
  'requires_confirmation'
);

create type public.recurring_status as enum (
  'active',
  'paused',
  'completed',
  'failed'
);

create type public.occurrence_status as enum (
  'pending',
  'posted',
  'skipped',
  'failed'
);

create table if not exists public.recurring_rules (
  id                  uuid primary key default gen_random_uuid(),
  organization_id     uuid not null references public.organizations (id) on delete cascade,

  name                text not null,
  transaction_type    public.transaction_type not null,
  -- Arguments for the record_* RPC this rule replays. Kept as jsonb because
  -- each flow takes a different shape; validated when the rule is created.
  template            jsonb not null,

  frequency           public.recurrence_frequency not null,
  interval_count      integer not null default 1,
  start_date          date not null,
  end_date            date,
  max_occurrences     integer,
  occurrences_created integer not null default 0,

  next_run_on         date,
  previous_run_on     date,

  mode                public.recurring_mode not null default 'requires_confirmation',
  status              public.recurring_status not null default 'active',
  failure_count       integer not null default 0,
  last_error          text,

  created_by          uuid references public.profiles (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint recurring_rules_name_length check (char_length(name) between 1 and 160),
  constraint recurring_rules_interval_positive check (interval_count between 1 and 365),
  constraint recurring_rules_max_occurrences_positive check (
    max_occurrences is null or max_occurrences > 0
  ),
  constraint recurring_rules_end_after_start check (
    end_date is null or end_date >= start_date
  ),
  constraint recurring_rules_template_is_object check (jsonb_typeof(template) = 'object'),
  constraint recurring_rules_id_org_unique unique (id, organization_id)
);

comment on table public.recurring_rules is
  'Templates that generate transactions on a schedule. The rule itself never '
  'touches the ledger; run_recurring_schedule() calls the ordinary posting RPCs.';
comment on column public.recurring_rules.next_run_on is
  'The next occurrence date not yet generated. Advanced only after an '
  'occurrence row exists, so a crash mid-run cannot skip a period.';

create index if not exists recurring_rules_org_status_idx
  on public.recurring_rules (organization_id, status);
create index if not exists recurring_rules_due_idx
  on public.recurring_rules (next_run_on)
  where status = 'active';
create index if not exists recurring_rules_created_by_idx
  on public.recurring_rules (created_by);

create trigger recurring_rules_set_updated_at
  before update on public.recurring_rules
  for each row execute function app.set_updated_at();

alter table public.recurring_rules enable row level security;

-- Commitments may be generated by a rule.
alter table public.commitments
  add constraint commitments_rule_same_org
  foreign key (recurring_rule_id, organization_id)
  references public.recurring_rules (id, organization_id) on delete set null;

-- ---------------------------------------------------------------------------
-- Occurrences — the idempotency ledger for the scheduler
-- ---------------------------------------------------------------------------
create table if not exists public.recurring_occurrences (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  rule_id         uuid not null,
  occurrence_date date not null,
  status          public.occurrence_status not null default 'pending',
  transaction_id  uuid,
  error_message   text,
  posted_at       timestamptz,
  created_at      timestamptz not null default now(),

  -- The whole idempotency guarantee, in one line.
  constraint recurring_occurrences_unique unique (rule_id, occurrence_date),
  constraint recurring_occurrences_id_org_unique unique (id, organization_id),
  constraint recurring_occurrences_posted_has_transaction check (
    status <> 'posted' or transaction_id is not null
  ),

  constraint recurring_occurrences_rule_same_org
    foreign key (rule_id, organization_id)
    references public.recurring_rules (id, organization_id) on delete cascade,
  constraint recurring_occurrences_transaction_same_org
    foreign key (transaction_id, organization_id)
    references public.transactions (id, organization_id) on delete restrict
);

comment on constraint recurring_occurrences_unique on public.recurring_occurrences is
  'Makes the scheduler idempotent: a second run for the same period cannot '
  'insert a second occurrence, so it cannot post a second transaction.';

create index if not exists recurring_occurrences_org_pending_idx
  on public.recurring_occurrences (organization_id, occurrence_date)
  where status = 'pending';
create index if not exists recurring_occurrences_rule_idx
  on public.recurring_occurrences (rule_id, occurrence_date desc);
create index if not exists recurring_occurrences_transaction_idx
  on public.recurring_occurrences (transaction_id) where transaction_id is not null;

alter table public.recurring_occurrences enable row level security;

-- ---------------------------------------------------------------------------
-- Date arithmetic
-- ---------------------------------------------------------------------------
-- Occurrence N is always measured from the start date, never from the previous
-- occurrence. Stepping iteratively would drift: 31 Jan + 1 month clamps to
-- 28 Feb, and the next step from there gives 28 Mar. Anchoring on the start
-- date gives 31 Jan, 28 Feb, 31 Mar — which is what "monthly on the 31st"
-- means to a human.
create or replace function app.nth_occurrence(
  p_start      date,
  p_frequency  public.recurrence_frequency,
  p_interval   integer,
  p_index      integer
)
returns date
language sql
immutable
set search_path = ''
as $$
  select case p_frequency
    when 'daily'     then p_start + make_interval(days   => p_interval * p_index)
    when 'weekly'    then p_start + make_interval(weeks  => p_interval * p_index)
    when 'monthly'   then p_start + make_interval(months => p_interval * p_index)
    when 'quarterly' then p_start + make_interval(months => p_interval * p_index * 3)
    when 'yearly'    then p_start + make_interval(years  => p_interval * p_index)
  end::date;
$$;

comment on function app.nth_occurrence(date, public.recurrence_frequency, integer, integer) is
  'Zero-based occurrence date, always measured from the start date so monthly '
  'rules anchored on the 29th-31st do not drift after a short month.';
